<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'article_cat_version' => '1.0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '18',
    'cat_name' => '健康资讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '0',
    'article_cat_version' => '1.0',
    'has_children' => '7',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '1',
    'article_cat_version' => '1.1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '新手上路3',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'article_cat_version' => '1.1',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '手机常识',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '手机常识 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '配送与支付 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '配送与支付 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '服务保证 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  8 => 
  array (
    'cat_id' => '9',
    'cat_name' => '联系我们 ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '联系我们 ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  9 => 
  array (
    'cat_id' => '10',
    'cat_name' => '会员中心',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  10 => 
  array (
    'cat_id' => '19',
    'cat_name' => '男科专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '18',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  11 => 
  array (
    'cat_id' => '17',
    'cat_name' => '妇科专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '18',
    'article_cat_version' => '1.1',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  12 => 
  array (
    'cat_id' => '21',
    'cat_name' => '风湿专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '18',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  13 => 
  array (
    'cat_id' => '22',
    'cat_name' => '消化专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '18',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  14 => 
  array (
    'cat_id' => '23',
    'cat_name' => '养生专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '1',
    'parent_id' => '18',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
  15 => 
  array (
    'cat_id' => '20',
    'cat_name' => '母婴专题',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '18',
    'article_cat_version' => '1.0',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  16 => 
  array (
    'cat_id' => '13',
    'cat_name' => '名医讲堂',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '中药养生；两性专区、疾病养生等图文文章展示。',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '18',
    'article_cat_version' => '1.1',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
);
?>